### PR TITLE
added recaptcha verification

### PR DESCRIPTION
**Pull request by okumujustine**
verifies the ReCaptcha from the backend.

### CODE REVIEW

**Comment by NickCallaghan** [comment]
@okumujustine Give me a shout if you need a hand getting the failing tests to pass

**Comment by okumujustine** [comment]
> @okumujustine Give me a shout if you need a hand getting the failing tests to pass

okay @NickCallaghan , and this is meant for testing purposes, the entire implementation will be moved to be part of the login process or under the login event button.

it's supposed to be tested by @seanmajorpayne and the backend team.

**Comment by NickCallaghan** [comment]
It looks like we have tests failing in the ci, so somebody needs a investigate. Could be the test needs updated. 

Looks like both unit and cypress test are failing, should be be a team effort to get it over the line. 

I suspect from a cypress front you’ll need to mock the new api call. It’s pretty easy,  l can walk you through.

**Comment by okumujustine** [comment]
> It looks like we have tests failing in the ci, so somebody needs a investigate. Could be the test needs updated. Looks like both unit and cypress test are failing, should be be a team effort to get it over the line. I suspect from a cypress front you’ll need to mock the new api call. It’s pretty easy, l can walk you through.
> […](#)
> Sent from my iPhone
> On 22 Aug 2021, at 18:04, Okumu Justine ***@***.***> wrote: ﻿ @okumujustine Give me a shout if you need a hand getting the failing tests to pass okay @NickCallaghan , and this is meant for testing purposes, the entire implementation will be moved to be part of the login process or under the login event button. it's supposed to be tested by @seanmajorpayne and the backend team. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

ooh, I get that, it will be great if you walk you through it. @NickCallaghan

**Review by rodriguesk — APPROVED** [review]
I've tested this and it all works great! good job.

**Pull request merged**
