### PR TITLE
Cm 1118 improved order of shared values screen

### PR DESCRIPTION
**Pull request by nbrix**
* Changed order of shared values screen

image

### CODE REVIEW

**Comment by rodriguesk** [comment]
@nbrix Here's the summary of the feedback for you from the meeting. Can you make these changes? 
Screen Shot 2022-10-19 at 11 13 40 AM

**Comment by nbrix** [comment]
@rodriguesk New layout
image

**Comment by nbrix** [comment]
@rodriguesk New layout
image
image

**Comment by rodriguesk** [comment]
This looks great! Except it looks like it doesn’t all fit on the page? Can some extra blank space be added to the bottom of the screen so it can fit with scrolling?

**Comment by nbrix** [comment]
I cut off the screenshot, but are you trying it and not able to see all the similarity score?
image

**Comment by rodriguesk** [comment]
I was just referring to the mobile screen and I mean on mobile when scrolling down it doesn't allow to scroll all the way for the final number on the bottom of the screen to show fully. It's a separate bug so if too hard to fix here or aren't seeing it then don't need to do it.

**Comment by rodriguesk** [comment]
Screen Shot 2022-10-21 at 11 28 00 AM
See this screenshot. The bug is caused from the bottom panel not being considered as blocking the content on the screen shown, when it actually does.

**Comment by rodriguesk** [comment]
@nbrix I checked it for your branch. The bug seems fixed for your branch but there is a background color bug occurring. See the screenshot. 
Screen Shot 2022-10-21 at 11 41 54 AM

**Comment by nbrix** [comment]
It seems to only occur with certain dimensions, but it's fine with phones. I'll try to figure out what's going on.
image

**Comment by nbrix** [comment]
Should be fixed

**Review by rodriguesk — APPROVED** [review]

**Pull request merged**
