### PR TITLE
New Conversation Page Structure 

### PR DESCRIPTION
**Pull request by okumujustine**
### Detailed information:
This PR implements the new conversation page designs with the functionalities.

## To test it
1 - Run the app
2 - login
3- Navigate to the Hub Page
4 - Compare the page to the [Designs on Figma](https://www.figma.com/design/ICtHOAJzuFnEG8ANfXeWix/cm_pwa_design?node-id=4791-21842&node-type=frame&t=mSVmYNTnfcDLU5Kt-0)

Screenshots
Screenshot 2024-10-19 at 2 52 09 PM
Screenshot 2024-10-19 at 2 52 45 PM
Screenshot 2024-10-19 at 2 52 55 PM
Screenshot 2024-10-19 at 2 53 08 PM
Screenshot 2024-10-19 at 2 53 19 PM
Screenshot 2024-10-19 at 2 53 28 PM

### CODE REVIEW

**Comment by okumujustine** [comment]
@Svenstar74 , @epixieme, it looks like I don't have the option to add reviewers to this PR, so could you add yourselves?

Below is the screenshot of the view I get
Screenshot 2024-10-19 at 2 38 40 PM

**Comment by okumujustine** [comment]
@epixieme , @rodriguesk , @Svenstar74

**Comment by epixieme** [comment]
@okumujustine  Just checking this Is this ready for review if so could you update the original notes as it says its a draft :-) thank you . I'll try and review this week if not it will be next week.

**Comment by okumujustine** [comment]
Yeah, it's ready

**Pull request closed without merging**
