### PR TITLE
cm-647 added recaptcha key and env

### PR DESCRIPTION
**Pull request by okumujustine**
## What I did

- [x] Added Recaptcha on the login page.

## Description
The login button is disabled until the ReCaptcha is verified.

## Demo

ezgif com-gif-maker (4)

## Reviewers
@NickCallaghan @rodriguesk

### CODE REVIEW

**Comment by NickCallaghan** [comment]
@okumujustine The site key is currently in the git repo.

**Comment by NickCallaghan** [comment]
Cancel that, i see it's an old one

**Review by NickCallaghan — DISMISSED** [review]

**Comment by rodriguesk** [comment]
@NickCallaghan is this ready to merge into develop so I can test devops things? Or is it guarenteed to fail in develop which is why it hasn't merged yet? If so, then I can keep making changing until it passes automated tests and that's how I could know if it is working... but if it is failing automated tests for different reasons then I can't fix any devops issues until this is in develop.

**Review by rodriguesk — APPROVED** [review]

**Comment by rodriguesk** [comment]
I think it's failing tests because recaptcha environment variables aren't working correctly? So I'll probably have to work on the devops stuff now? That's assuming once I get the react app recaptcha sitekey correctly into the environment variable that then it would deactivate the recaptcha so that the automated tests pass?

**Comment by rodriguesk** [comment]
see: 
https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

I'd like to run automated tests with reCAPTCHA. What should I do?
For reCAPTCHA v3, create a separate key for testing environments. Scores may not be accurate as reCAPTCHA v3 relies on seeing real traffic.

For reCAPTCHA v2, use the following test keys. You will always get No CAPTCHA and all verification requests will pass.

Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

**Review by rodriguesk — DISMISSED** [review]
I need to fix the devops aspects so this shouldn't be merged into develop until I fix the devops stuff. I need to enable environment variables in a way beyond storing them in the header. I've seen some websites describing how to do this so I'll start working on it now. @y-himanen

**Comment by NickCallaghan** [comment]
@rodriguesk For just now the app fall back to the google provided test site key if the env variable is missing which will be fine for merging at least as far as develop.

**Review by NickCallaghan — APPROVED** [review]

**Review by NickCallaghan — APPROVED** [review]

**Pull request merged**
