### PR TITLE
Cm-765 frontend localhost container support

### PR DESCRIPTION
**Pull request by rodriguesk**
*can now code in docker on the front end (this is essential because our devopps infrastructure only works on mac/linux/unix as @JamesAKing discovered. So if any frontend members or testers have PC they won't be able to run the front end or code on the frontend. This solves this issue. They just have to code from the docker (it doesn't change anything just the npm command they need to use only).
*- made 4 dockerfiles (1 standard Dockerfile that doesn’t have any
environment variables defined at all and require env variables to be
passed to the docker run command upon running the container. Then 4
other dockerfiles were made (1 for production, 1 for local, 1 for
test container, and 1 for development while using the container).

*Updated the config.yml to use the new Dockerfiles
*updated the docker:run script in package.json to use correct
environment variable. this docker is just for replicating production version nginx context. It shouldn't be used for developing in the container (the docker:dev:run:... scripts should be used for that)
* the docker:dev:run:... scripts are operating system dependent so ensure to use the right one! I've only been able to test the mac one. 

**Do we want production version to run the environment to have the
environment variables in the header too???

Do we want the docker version of the local frontend to run on the same
port as the local developer version of the app? (3000? OR 8080?)**

### CODE REVIEW

**Comment by rodriguesk** [comment]
@NickCallaghan why does this fail Percy tests? How can I check them and get more details about the specific parts that failed?

**Comment by NickCallaghan** [comment]
Percy is a visual snapshotting tool, it's not failing just needs approved if it thinks there are any visual changes. 

I've approved them and sent you a percy join link

**Review by NickCallaghan — APPROVED** [review]

**Review by NickCallaghan — APPROVED** [review]

**Comment by NickCallaghan** [comment]
I'm not convinced that trying to run the container while developing really adds anything other than complexity, but if people want to use it fair enough. 

The issue James had was a git one, nothing to do with docker.

**Comment by rodriguesk** [comment]
The npm start and npm dev commands currently will not run on PC. So it will be an issue for anyone who doesn’t have a mac of Linux machine.

There could be separate npm start commands that are operating system dependent, but that doesn’t mesh well with React app standards.

The readme and QuickStart need to be updated accordingly.

**Pull request merged**
