### PR TITLE
fix: env file for api url

### PR DESCRIPTION
**Pull request by thiyagarajan-angappan**
# Using deployed PROD api
### Issue Description
We have an environment variable REACT_APP_API_URL configured with the backend API url in Azure but application doesn't seem to be aware of it. Hence we are facing an `undefined` value in the react application

### Frontend configuration change
- `.env.production` file is added to hold the prod backend url
- This will be picked up by the build scripts and made available for the application

---
### CRA - react-scripts
Environment variables are setup during the build process of react scripts
- [CRA build script](https://github.com/facebook/create-react-app/blob/025f2739ceb459c79a281ddc6e60d7fd7322ca24/packages/react-scripts/scripts/build.js#L23
)
- [CRA environment variable setup during build process](https://github.com/facebook/create-react-app/blob/025f2739ceb459c79a281ddc6e60d7fd7322ca24/packages/react-scripts/config/env.js#L104)

### Azure Application Settings
REACT_APP_API_URL` is defined in Azure application settings but by the time the code reaches azure the env variables are already set. Azure does inject the variable to the container. But in case of a react app bundled to a static html and not rendered server side, the container variable is not utilized
- [Configuration using docker compose](https://www.freecodecamp.org/news/how-to-implement-runtime-environment-variables-with-create-react-app-docker-and-nginx-7f9d42a91d70/)
- [Configuration using placeholders in html as one answer](https://social.msdn.microsoft.com/Forums/en-US/b5cf1c66-0026-426c-9993-8092457c3ff6/reactjs-apps-on-webapps-how-to-access-appsettings?forum=windowsazurewebsitespreview)

### Next steps
- could we have a placeholder or variable in the `.env` file, say `REACT_APP_API_URL=%API_URL%`
- access value from azure's application settings during dockerfile execution
- replace `%API_URL%` in `.env` file with actual URL from above

## Testing
- console.log
image

- 200 OK
image

- response message
image

## Documentation
- would like to place the above info, links and any solution that we arrive after this someplace... update in PT ?

### CODE REVIEW

**Review by johols — APPROVED** [review]
Good solution!

**Comment by rolandoldengarm** [comment]
This shouldn't be necessary. The app setting "REACT_APP_API_URL" should be available immediately in the container as environment variable without any scripts from our side.

See documentation here: https://docs.microsoft.com/en-us/azure/app-service/configure-common

> In App Service, app settings are variables passed as environment variables to the application code. For Linux apps and custom containers, App Service passes app settings to the container using the --env flag to set the environment variable in the container.

**Review by rolandoldengarm — CHANGES_REQUESTED** [review]
Hardcoding the URL will break if we e.g. introduce multiple environments or use a custom domain name.

**Review by rolandoldengarm — APPROVED** [review]

**Comment by NickCallaghan** [comment]
Well done @thiyagarajan-angappan! That's great work!

**Review by NickCallaghan — APPROVED** [review]

**Comment by thiyagarajan-angappan** [comment]
> Good investigation. I'd recommend against hardcoding URL's as they are generated in the infra project and will change in the future.

Yes ! The URL should be external to application so we can update at runtime when the domain changes. Would be nice if we could meet and discuss sometime next week in zoom

**Pull request merged**
