### PR TITLE
CM-1071: Quiz id intersection user A and user B

### PR DESCRIPTION
**Pull request by Svenstar74**
Need some advice on this one.
It feels like it works as it should, although sometimes after the last question has been answered, the submitScores post request results in a 500 error and then the page won't load.

### CODE REVIEW

**Review by NickCallaghan — APPROVED** [review]

**Review by NickCallaghan — APPROVED** [review]

**Comment by rodriguesk** [comment]
Can someone fix the tests in the develop branch? I fixed a copy issue and didn’t realize it would cause tests to fail.

**Comment by Svenstar74** [comment]
Fixed them in this PR
https://github.com/ClimateMind/climatemind-frontend/pull/310

**Comment by rodriguesk** [comment]
@NickCallaghan @Svenstar74 I'm reviewing this PR now. There are some things that might need to be changed. Please do not merge to develop yet. I'll comment here what the issues are (assuming after I double check they still occur). Thanks!

**Comment by rodriguesk** [comment]
@Svenstar74 here's my feedback https://stanford.zoom.us/rec/play/-NoZWYm2mF3C0ka49B1IT5xLP7URSj9VI7BPR7DyzOL3QXbV0kRRwR9wzmd9Kjl8fi9L7OtPaMDkCVw.VrZYnMn6CkbyJQ4-
If this is just too complicated then worst case solution is to make it so user A and user B quizID is never remembered beyond their session. 

FYI @NickCallaghan regarding current behavior and how we'd want it to behave.

**Pull request closed without merging**
